cmc.greetings_settings:
  type: config_object
  label: 'Custom Multilingual Configurations'
  mapping:
    greeting:
      type: label
      label: 'Your greeting for the site visitors'
    greeting_summary:
      type: text
      label: 'Your detailed message for the site visitors'
